export const AFRICAN_COUNTRIES = [
  'Algeria',
  'Angola',
  'Benin',
  'Botswana',
  'Burkina Faso',
  'Burundi',
  'Cameroon',
  'Cape Verde',
  'Central African Republic',
  'Chad',
  'Comoros',
  'Congo',
  'DR Congo',
  "Côte d'Ivoire",
  'Djibouti',
  'Egypt',
  'Equatorial Guinea',
  'Eritrea',
  'Eswatini',
  'Ethiopia',
  'Gabon',
  'Gambia',
  'Ghana',
  'Guinea',
  'Guinea-Bissau',
  'Kenya',
  'Lesotho',
  'Liberia',
  'Libya',
  'Madagascar',
  'Malawi',
  'Mali',
  'Mauritania',
  'Mauritius',
  'Morocco',
  'Mozambique',
  'Namibia',
  'Niger',
  'Nigeria',
  'Rwanda',
  'São Tomé and Príncipe',
  'Senegal',
  'Seychelles',
  'Sierra Leone',
  'Somalia',
  'South Africa',
  'South Sudan',
  'Sudan',
  'Tanzania',
  'Togo',
  'Tunisia',
  'Uganda',
  'Zambia',
  'Zimbabwe'
];

// Map from URL-friendly codes (like used on /countries) to full country names
export const AFRICAN_COUNTRY_CODES = {
  'algeria': 'Algeria',
  'angola': 'Angola',
  'benin': 'Benin',
  'botswana': 'Botswana',
  'burkina-faso': 'Burkina Faso',
  'burundi': 'Burundi',
  'cameroon': 'Cameroon',
  'cape-verde': 'Cape Verde',
  'central-african-republic': 'Central African Republic',
  'chad': 'Chad',
  'comoros': 'Comoros',
  'congo': 'Congo',
  'dr-congo': 'DR Congo',
  'ivory-coast': "Côte d'Ivoire",
  'djibouti': 'Djibouti',
  'egypt': 'Egypt',
  'equatorial-guinea': 'Equatorial Guinea',
  'eritrea': 'Eritrea',
  'eswatini': 'Eswatini',
  'ethiopia': 'Ethiopia',
  'gabon': 'Gabon',
  'gambia': 'Gambia',
  'ghana': 'Ghana',
  'guinea': 'Guinea',
  'guinea-bissau': 'Guinea-Bissau',
  'kenya': 'Kenya',
  'lesotho': 'Lesotho',
  'liberia': 'Liberia',
  'libya': 'Libya',
  'madagascar': 'Madagascar',
  'malawi': 'Malawi',
  'mali': 'Mali',
  'mauritania': 'Mauritania',
  'mauritius': 'Mauritius',
  'morocco': 'Morocco',
  'mozambique': 'Mozambique',
  'namibia': 'Namibia',
  'niger': 'Niger',
  'nigeria': 'Nigeria',
  'rwanda': 'Rwanda',
  'sao-tome-and-principe': 'São Tomé and Príncipe',
  'senegal': 'Senegal',
  'seychelles': 'Seychelles',
  'sierra-leone': 'Sierra Leone',
  'somalia': 'Somalia',
  'south-africa': 'South Africa',
  'south-sudan': 'South Sudan',
  'sudan': 'Sudan',
  'tanzania': 'Tanzania',
  'togo': 'Togo',
  'tunisia': 'Tunisia',
  'uganda': 'Uganda',
  'zambia': 'Zambia',
  'zimbabwe': 'Zimbabwe'
};


